language: objective-c
osx_image: xcode7.3
xcode_project: Relayout.xcodeproj
xcode_sdk: iphonesimulator9.3

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xctool clean build -project Relayout.xcodeproj -scheme "Relayout" -sdk iphonesimulator
- xctool test -project Relayout.xcodeproj -scheme "Relayout" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 5s"
- xctool clean build -project Relayout.xcodeproj -scheme "Relayout" -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 1080p"
- xctool test -project Relayout.xcodeproj -scheme "Relayout" -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 1080p" 
- xctool clean build -project Relayout.xcodeproj -scheme "Relayout" -sdk macosx
- xctool test -project Relayout.xcodeproj -scheme "Relayout" -sdk macosx
- xctool clean build -project Relayout.xcodeproj -scheme "Sample App" -sdk iphonesimulator
- carthage build --no-skip-current
- pod lib lint
- swift build

before_deploy:
- carthage archive Relayout

deploy:
  provider: releases
  api_key: "$GITHUB_API_KEY"
  file: 
    - "Relayout.framework.zip"
  skip_cleanup: true
  on:
    repo: stevestreza/Relayout
    tags: true

